sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y autoconf build-essential pkg-config libboost-dev libgmp3-dev libxml2-dev liblua5.1-0-dev libmysqlclient-dev libcrypto++-dev ccache libboost-filesystem-dev libboost-regex-dev libboost-system-dev libboost-thread-dev libssl-dev lua5.1 libncurses5-dev

script:
  - cd source
  - sh ./autogen.sh
  - ./configure --enable-mysql --enable-server-diag
  - make
